### ISSUE TITLE
NullPointerException in DefaultSmppSession

### ISSUE THREAD

**Issue by dmitry-sukhovilin** [twitter/cloudhopper-smpp#48]
Hello,
I got NullPointerException when I set WriteTimeout of object SmppSessionConfiguration to 1 (very slow value).

java.lang.NullPointerException: null
	at com.cloudhopper.smpp.impl.DefaultSmppSession

.sendRequestPdu(DefaultSmppSession.java:531) ~[ch-smpp-5.0.4.jar:5.0.4]

It happened because channelFuture.getCause() return null
file: DefaultSmppSession.java
line: 531
Screenshot of debugger is attached.
Thank you.

![screenshot from 2013-12-14 03 02 33](https://f.cloud.github.com/assets/5786379/1746882/9d56b68e-644b-11e3-8b2c-9a326ac56091.png)

**Comment by xgp** [comment]
1 is 1ms. ChannelFuture.getCause() is null because it hasn't yet completed. Was the NPE thrown in your code or the library? Constructing an SmppChannelException with a null throwable shouldn't throw an NPE. Please provide a full stack trace.

**Comment by stela** [comment]
From the screenshot you can see ChannelFuture.getCause() is null and evaluating channelFuture.getCause().getMessage() then causes an NPE. That ChannelFuture.getCause() returns null is normal when await(1) finishes after 1ms (guess due to a timeout, the future could in theory have been cancelled).

From the screenshot you can also see that the NPE occurs in DefaultSmppSession, which is part of the library. Here's the location: https://github.com/twitter/cloudhopper-smpp/blob/e2e15df3/src/main/java/com/cloudhopper/smpp/impl/DefaultSmppSession.java#L535

On the master branch the code still looks similar, https://github.com/twitter/cloudhopper-smpp/blob/master/src/main/java/com/cloudhopper/smpp/impl/DefaultSmppSession.java#L535

**Comment by xgp** [comment]
Thanks. I missed the call to getMessage(). I will update this in the netty4 branch, which will be released as 6.0.0 this month. 7a0214b853c801eb462f11899c0193c1809d281d

**Comment by stela** [comment]
@xgp There are multiple instances of getCause().getMessage(), besides the one in sendRequestPdu() you fixed there's similar code in sendResponsePdu(). If you look for usages of getCause(), you'll find other potential NPEs in DefaultSmppClient and UnboundSmppSession as well.

**Comment by xgp** [comment]
Thanks again. Added checks in DefaultSmppClient and UnboundSmppSession. 6a42e6ada5b7f5d85c430158b69b2f513fc921ed
