### ISSUE TITLE
SMPP session with automatic enquireLink an re-bind when needed

### ISSUE THREAD

**Issue by toelen** [twitter/cloudhopper-smpp#7]
Hi,

is there an example of a long-lived smpp session. I have requirement for a very long-lived smpp client session with automatic re-bind and enquireLink. What would you suggest to make as much use as possible of the existing session event notifications and the existing excutors?

Regards,
Leen

**Comment by NaveenNew** [comment]
Is it possible to send messages to SMSC using one Smppsession (or a session that lasts long )because binding & unbinding for every single msg has resulted in creating large number of  bind requests at SMSC . 

Due to this load ,SMSC is failing to receive bind requests and we are receiving the error "com.cloudhopper.smpp.type.SmppTimeoutException: Unable to get response within [3000 ms]"
@jjlauer @idpromnut @tester5 @toelen @tmuldoon-aimia

**Comment by idpromnut** [comment]
In fact, it is actually in the spec that you can send multiple messages
using the same session (and preferred to be this way!).

idpromnut

**Comment by NaveenNew** [comment]
Can you share the code or a snippet  to implement this @idpromnut .Thanks
