### ISSUE TITLE
Unable to send long message which  is greater than 255 chars  using cloudhopper

### ISSUE THREAD

**Issue by New009** [twitter/cloudhopper-smpp#72]
Hi All,

When we are trying to push a longer message which is more than 255 characters length, i am getting the below error message from cloud hopper. But in our case, the SMSC element is handling the split of longer messages. We are  requested not to split at our end. 

com.cloudhopper.smpp.type.SmppInvalidArgumentException: A short message in a PDU can only be a max of 255 bytes [actual=535]; use optional parameter message_payload as an alternative 

How can we make the cloud hopper API by pass this validation and push the message directly to SMSC element so that SMSC takes care of split logic. 

Thanks

**Comment by Madhukiran81** [comment]
can any one share, how to set the optional parameters (TLV) to use message_Payload to send the message more than 255 characters.
and one more is if use use message_payload do we need to set the sm_length as 0.??
if yes how can we set it to 0 because in submit_sm it is set to private like this.
// setSmLength() is private as it's set to length of the message
  private void setSmLength(short value) {
    smLength = value;
  }

**Comment by lafod** [comment]
if (textBytes != null && textBytes.length > 255) {
                 submitMsg.addOptionalParameter(new Tlv(SmppConstants.TAG_MESSAGE_PAYLOAD, textBytes, "message_payload"));
             }else{
                 submitMsg.setShortMessage(textBytes);
             }
